global_analytics_project:
  target: dev
  outputs:
    dev:
      type: mysql
      server: "{{env_var('MYSQL_HOST', '127.0.0.1')}}"
      port: 3306
      database: blinkit_business_marts
      schema: blinkit_business_marts
      username: "{{env_var('MYSQL_USER')}}"
      password: "{{env_var('MYSQL_PASSWORD')}}"
      driver: MySQL ODBC 8.0 ANSI Driver
