name: dbt_main_build

on:
  push:
    branches:
      - main

jobs:
  run-dbt-main:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python venv and install dbt
        run: |
          python3.11 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install "protobuf<5" "dbt-core==1.7.9" "dbt-mysql==1.7.0"
          echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
          echo "PATH=$PWD/.venv/bin:$PATH" >> $GITHUB_ENV

      - name: Set up dbt profile
        run: |
          mkdir -p ~/.dbt
          cp .github/profiles.yml ~/.dbt/profiles.yml

      - name: Run dbt build on main
        run: dbt build --target dev
        env:
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}

      # ✅ Save manifest for PR jobs
      - name: Save dbt manifest to cache
        uses: actions/cache/save@v3
        with:
          path: target/manifest.json
          key: dbt-manifest-main
